#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SocialNetwork.Droid.Resource", IsApplication=true)]

namespace SocialNetwork.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Controls.Resource.String.library_name = global::SocialNetwork.Droid.Resource.String.library_name;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circleColor = global::SocialNetwork.Droid.Resource.Attribute.circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circularProgressBarStyle = global::SocialNetwork.Droid.Resource.Attribute.circularProgressBarStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_gravity = global::SocialNetwork.Droid.Resource.Attribute.circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate = global::SocialNetwork.Droid.Resource.Attribute.circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate_interval = global::SocialNetwork.Droid.Resource.Attribute.circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_marker_progress = global::SocialNetwork.Droid.Resource.Attribute.circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress = global::SocialNetwork.Droid.Resource.Attribute.circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_background_color = global::SocialNetwork.Droid.Resource.Attribute.circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_color = global::SocialNetwork.Droid.Resource.Attribute.circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_stroke_width = global::SocialNetwork.Droid.Resource.Attribute.circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate = global::SocialNetwork.Droid.Resource.Attribute.indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate_interval = global::SocialNetwork.Droid.Resource.Attribute.indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.innerSize = global::SocialNetwork.Droid.Resource.Attribute.innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.max = global::SocialNetwork.Droid.Resource.Attribute.max;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinned = global::SocialNetwork.Droid.Resource.Attribute.pinned;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinnedDrawable = global::SocialNetwork.Droid.Resource.Attribute.pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progress = global::SocialNetwork.Droid.Resource.Attribute.progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressButtonStyle = global::SocialNetwork.Droid.Resource.Attribute.progressButtonStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressColor = global::SocialNetwork.Droid.Resource.Attribute.progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.shadowDrawable = global::SocialNetwork.Droid.Resource.Attribute.shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.unpinnedDrawable = global::SocialNetwork.Droid.Resource.Attribute.unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_circle_color = global::SocialNetwork.Droid.Resource.Color.progress_default_circle_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_progress_color = global::SocialNetwork.Droid.Resource.Color.progress_default_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_dark = global::SocialNetwork.Droid.Resource.Color.refractored_background_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_dark = global::SocialNetwork.Droid.Resource.Color.refractored_background_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_light = global::SocialNetwork.Droid.Resource.Color.refractored_background_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_light = global::SocialNetwork.Droid.Resource.Color.refractored_background_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark = global::SocialNetwork.Droid.Resource.Color.refractored_bright_foreground_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark_disabled = global::SocialNetwork.Droid.Resource.Color.refractored_bright_foreground_dark_disabled;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_dark = global::SocialNetwork.Droid.Resource.Color.refractored_bright_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_light = global::SocialNetwork.Droid.Resource.Color.refractored_bright_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_dark = global::SocialNetwork.Droid.Resource.Color.refractored_bright_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_light = global::SocialNetwork.Droid.Resource.Color.refractored_bright_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_light = global::SocialNetwork.Droid.Resource.Color.refractored_bright_foreground_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_dark = global::SocialNetwork.Droid.Resource.Color.refractored_dim_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_light = global::SocialNetwork.Droid.Resource.Color.refractored_dim_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_dark = global::SocialNetwork.Droid.Resource.Color.refractored_dim_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_light = global::SocialNetwork.Droid.Resource.Color.refractored_dim_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_dark = global::SocialNetwork.Droid.Resource.Color.refractored_highlighted_text_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_light = global::SocialNetwork.Droid.Resource.Color.refractored_highlighted_text_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_dark = global::SocialNetwork.Droid.Resource.Color.refractored_hint_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_light = global::SocialNetwork.Droid.Resource.Color.refractored_hint_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_bright = global::SocialNetwork.Droid.Resource.Color.refractored_holo_blue_bright;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_dark = global::SocialNetwork.Droid.Resource.Color.refractored_holo_blue_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_light = global::SocialNetwork.Droid.Resource.Color.refractored_holo_blue_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_dark = global::SocialNetwork.Droid.Resource.Color.refractored_holo_green_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_light = global::SocialNetwork.Droid.Resource.Color.refractored_holo_green_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_dark = global::SocialNetwork.Droid.Resource.Color.refractored_holo_orange_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_light = global::SocialNetwork.Droid.Resource.Color.refractored_holo_orange_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_purple = global::SocialNetwork.Droid.Resource.Color.refractored_holo_purple;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_dark = global::SocialNetwork.Droid.Resource.Color.refractored_holo_red_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_light = global::SocialNetwork.Droid.Resource.Color.refractored_holo_red_light;
			global::com.refractored.monodroidtoolkit.Resource.Dimension.progress_inner_size = global::SocialNetwork.Droid.Resource.Dimension.progress_inner_size;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_pinned = global::SocialNetwork.Droid.Resource.Drawable.pin_progress_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_shadow = global::SocialNetwork.Droid.Resource.Drawable.pin_progress_shadow;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_unpinned = global::SocialNetwork.Droid.Resource.Drawable.pin_progress_unpinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_normal_holo = global::SocialNetwork.Droid.Resource.Drawable.scrubber_control_normal_holo;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_pressed_holo = global::SocialNetwork.Droid.Resource.Drawable.scrubber_control_pressed_holo;
			global::com.refractored.monodroidtoolkit.Resource.Id.bottom = global::SocialNetwork.Droid.Resource.Id.bottom;
			global::com.refractored.monodroidtoolkit.Resource.Id.center = global::SocialNetwork.Droid.Resource.Id.center;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_horizontal = global::SocialNetwork.Droid.Resource.Id.center_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_vertical = global::SocialNetwork.Droid.Resource.Id.center_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip = global::SocialNetwork.Droid.Resource.Id.clip;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_horizontal = global::SocialNetwork.Droid.Resource.Id.clip_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_vertical = global::SocialNetwork.Droid.Resource.Id.clip_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.end = global::SocialNetwork.Droid.Resource.Id.end;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill = global::SocialNetwork.Droid.Resource.Id.fill;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_horizontal = global::SocialNetwork.Droid.Resource.Id.fill_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_vertical = global::SocialNetwork.Droid.Resource.Id.fill_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.left = global::SocialNetwork.Droid.Resource.Id.left;
			global::com.refractored.monodroidtoolkit.Resource.Id.right = global::SocialNetwork.Droid.Resource.Id.right;
			global::com.refractored.monodroidtoolkit.Resource.Id.start = global::SocialNetwork.Droid.Resource.Id.start;
			global::com.refractored.monodroidtoolkit.Resource.Id.top = global::SocialNetwork.Droid.Resource.Id.top;
			global::com.refractored.monodroidtoolkit.Resource.Integer.circular_indeterminent_interval = global::SocialNetwork.Droid.Resource.Integer.circular_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Integer.progressbutton_indeterminent_interval = global::SocialNetwork.Droid.Resource.Integer.progressbutton_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBar = global::SocialNetwork.Droid.Resource.Style.CircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBarLight = global::SocialNetwork.Droid.Resource.Style.CircularProgressBarLight;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton = global::SocialNetwork.Droid.Resource.Style.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton_Pin = global::SocialNetwork.Droid.Resource.Style.ProgressButton_Pin;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_gravity = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_color = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width = global::SocialNetwork.Droid.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_clickable = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_android_clickable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_focusable = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_android_focusable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_selectableItemBackground = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_android_selectableItemBackground;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_circleColor = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate_interval = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_innerSize = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_max = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_max;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinned = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinnedDrawable = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progress = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progressColor = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_shadowDrawable = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_unpinnedDrawable = global::SocialNetwork.Droid.Resource.Styleable.ProgressButton_unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme = global::SocialNetwork.Droid.Resource.Styleable.Theme;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme_circularProgressBarStyle = global::SocialNetwork.Droid.Resource.Styleable.Theme_circularProgressBarStyle;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SocialNetwork.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SocialNetwork.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int auxiliary_view_position = 2130771972;
			
			// aapt resource value: 0x7f01000f
			public const int circleColor = 2130771983;
			
			// aapt resource value: 0x7f010020
			public const int circularProgressBarStyle = 2130772000;
			
			// aapt resource value: 0x7f010018
			public const int circular_gravity = 2130771992;
			
			// aapt resource value: 0x7f01001e
			public const int circular_indeterminate = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int circular_indeterminate_interval = 2130771999;
			
			// aapt resource value: 0x7f01001b
			public const int circular_marker_progress = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int circular_progress = 2130771994;
			
			// aapt resource value: 0x7f01001d
			public const int circular_progress_background_color = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int circular_progress_color = 2130771996;
			
			// aapt resource value: 0x7f010019
			public const int circular_stroke_width = 2130771993;
			
			// aapt resource value: 0x7f010006
			public const int confirm_logout = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int foreground_color = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int horizontal_alignment = 2130771973;
			
			// aapt resource value: 0x7f010016
			public const int indeterminate = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int indeterminate_interval = 2130771991;
			
			// aapt resource value: 0x7f010014
			public const int innerSize = 2130771988;
			
			// aapt resource value: 0x7f01000b
			public const int is_cropped = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int login_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int logout_text = 2130771976;
			
			// aapt resource value: 0x7f01000e
			public const int max = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int object_id = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int object_type = 2130771970;
			
			// aapt resource value: 0x7f010015
			public const int pinned = 2130771989;
			
			// aapt resource value: 0x7f010011
			public const int pinnedDrawable = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int preset_size = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int progress = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int progressButtonStyle = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int progressColor = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int shadowDrawable = 2130771987;
			
			// aapt resource value: 0x7f010003
			public const int style = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int tooltip_mode = 2130771977;
			
			// aapt resource value: 0x7f010012
			public const int unpinnedDrawable = 2130771986;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_button_background_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_button_background_color_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_button_background_color_pressed = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_button_like_background_color_selected = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_button_login_silver_background_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_button_login_silver_background_color_pressed = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_button_send_background_color = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_button_send_background_color_pressed = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_likeboxcountview_border_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_likeboxcountview_text_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_likeview_text_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_share_button_text_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int progress_default_circle_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int progress_default_progress_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int refractored_background_dark = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int refractored_background_holo_dark = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int refractored_background_holo_light = 2131034133;
			
			// aapt resource value: 0x7f050010
			public const int refractored_background_light = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int refractored_bright_foreground_dark = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int refractored_bright_foreground_dark_disabled = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int refractored_bright_foreground_disabled_holo_dark = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int refractored_bright_foreground_disabled_holo_light = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int refractored_bright_foreground_holo_dark = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int refractored_bright_foreground_holo_light = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int refractored_bright_foreground_light = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int refractored_dim_foreground_disabled_holo_dark = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int refractored_dim_foreground_disabled_holo_light = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int refractored_dim_foreground_holo_dark = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int refractored_dim_foreground_holo_light = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int refractored_highlighted_text_holo_dark = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int refractored_highlighted_text_holo_light = 2131034145;
			
			// aapt resource value: 0x7f05001c
			public const int refractored_hint_foreground_holo_dark = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int refractored_hint_foreground_holo_light = 2131034143;
			
			// aapt resource value: 0x7f05002b
			public const int refractored_holo_blue_bright = 2131034155;
			
			// aapt resource value: 0x7f050025
			public const int refractored_holo_blue_dark = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int refractored_holo_blue_light = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int refractored_holo_green_dark = 2131034150;
			
			// aapt resource value: 0x7f050023
			public const int refractored_holo_green_light = 2131034147;
			
			// aapt resource value: 0x7f05002a
			public const int refractored_holo_orange_dark = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int refractored_holo_orange_light = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int refractored_holo_purple = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int refractored_holo_red_dark = 2131034151;
			
			// aapt resource value: 0x7f050024
			public const int refractored_holo_red_light = 2131034148;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_likeboxcountview_border_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_likeboxcountview_border_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_likeboxcountview_caret_height = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_likeboxcountview_caret_width = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_likeboxcountview_text_padding = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_likeboxcountview_text_size = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_likeview_edge_padding = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_likeview_internal_padding = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_likeview_text_size = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_profilepictureview_preset_size_large = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_share_button_padding_bottom = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_share_button_padding_left = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_share_button_padding_right = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_share_button_padding_top = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_share_button_text_size = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_tooltip_horizontal_padding = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int progress_inner_size = 2131099667;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_button_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_button_like_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_like_icon_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_login_silver_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_send_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_send_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_close = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_profile_picture_blank_portrait = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_profile_picture_blank_square = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_tooltip_black_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_tooltip_black_bottomnub = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_tooltip_black_topnub = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_tooltip_black_xout = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_tooltip_blue_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_tooltip_blue_bottomnub = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_tooltip_blue_topnub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_blue_xout = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int correct8 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int logo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int messenger_bubble_large_blue = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int messenger_bubble_large_white = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int messenger_bubble_small_blue = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int messenger_bubble_small_white = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int messenger_button_blue_bg_round = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int messenger_button_blue_bg_selector = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int messenger_button_send_round_shadow = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int messenger_button_white_bg_round = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int messenger_button_white_bg_selector = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int monoandroidsplash = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int pin_progress_pinned = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int pin_progress_shadow = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int pin_progress_unpinned = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int placeholder = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int remove11 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int scrubber_control_normal_holo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int scrubber_control_pressed_holo = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Transparent = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000c
			public const int automatic = 2131296268;
			
			// aapt resource value: 0x7f090006
			public const int bottom = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int box_count = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int button = 2131296260;
			
			// aapt resource value: 0x7f090009
			public const int center = 2131296265;
			
			// aapt resource value: 0x7f090012
			public const int center_horizontal = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int center_vertical = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int clip = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int clip_horizontal = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int clip_vertical = 2131296278;
			
			// aapt resource value: 0x7f09001e
			public const int com_facebook_body_frame = 2131296286;
			
			// aapt resource value: 0x7f090020
			public const int com_facebook_button_xout = 2131296288;
			
			// aapt resource value: 0x7f09001c
			public const int com_facebook_fragment_container = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int com_facebook_login_activity_progress_bar = 2131296285;
			
			// aapt resource value: 0x7f090022
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int com_facebook_tooltip_bubble_view_text_body = 2131296289;
			
			// aapt resource value: 0x7f09001f
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131296287;
			
			// aapt resource value: 0x7f09000d
			public const int display_always = 2131296269;
			
			// aapt resource value: 0x7f090017
			public const int end = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int fill = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int fill_horizontal = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int fill_vertical = 2131296282;
			
			// aapt resource value: 0x7f090007
			public const int inline = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int large = 2131296271;
			
			// aapt resource value: 0x7f09000a
			public const int left = 2131296266;
			
			// aapt resource value: 0x7f090023
			public const int messenger_send_button = 2131296291;
			
			// aapt resource value: 0x7f09000e
			public const int never_display = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int normal = 2131296272;
			
			// aapt resource value: 0x7f090000
			public const int open_graph = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int page = 2131296257;
			
			// aapt resource value: 0x7f09000b
			public const int right = 2131296267;
			
			// aapt resource value: 0x7f090011
			public const int small = 2131296273;
			
			// aapt resource value: 0x7f090005
			public const int standard = 2131296261;
			
			// aapt resource value: 0x7f09001b
			public const int start = 2131296283;
			
			// aapt resource value: 0x7f090008
			public const int top = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int unknown = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public const int circular_indeterminent_interval = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int progressbutton_indeterminent_interval = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_activity_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_login_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_tooltip_bubble = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int messenger_button_send_blue_large = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int messenger_button_send_blue_round = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int messenger_button_send_blue_small = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int messenger_button_send_white_large = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int messenger_button_send_white_round = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int messenger_button_send_white_small = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_image_download_unknown_error = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_internet_permission_error_message = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int com_facebook_internet_permission_error_title = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_facebook_like_button_liked = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_facebook_like_button_not_liked = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int com_facebook_loading = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_loginview_cancel_action = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_loginview_log_in_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_loginview_log_in_button_long = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_loginview_log_out_action = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_loginview_log_out_button = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_loginview_logged_in_as = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_loginview_logged_in_using_facebook = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int com_facebook_send_button_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int com_facebook_share_button_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int com_facebook_tooltip_default = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int library_name = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int messenger_send_button_text = 2130968594;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070017
			public const int CircularProgressBar = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int CircularProgressBarLight = 2131165208;
			
			// aapt resource value: 0x7f070000
			public const int MessengerButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MessengerButton_Blue = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MessengerButton_Blue_Large = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MessengerButton_Blue_Small = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MessengerButton_White = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int MessengerButton_White_Large = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int MessengerButton_White_Small = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int MessengerButtonText = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int MessengerButtonText_Blue = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int MessengerButtonText_Blue_Large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int MessengerButtonText_Blue_Small = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int MessengerButtonText_White = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int MessengerButtonText_White_Large = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int MessengerButtonText_White_Small = 2131165197;
			
			// aapt resource value: 0x7f070019
			public const int Mono_Android_Theme_Splash = 2131165209;
			
			// aapt resource value: 0x7f070015
			public const int ProgressButton = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int ProgressButton_Pin = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int Theme_Splash = 2131165210;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_button = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_button_like = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_button_send = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_button_share = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_loginview_default_style = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_loginview_silver_style = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int tooltip_bubble_text = 2131165204;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[] {
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] ProgressButton = new int[] {
					16842970,
					16842981,
					16843534,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[] {
					2130772000};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
